name: Terraform AWS Destroy

on:
  workflow_dispatch: # Manually triggered

jobs:
  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4 # Node.js 20 compatible

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3 # Node.js 20 compatible
      with:
        terraform_version: 1.0.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3 # Node.js 16, will soon run on Node.js 20
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=tfplan-destroy

    - name: Terraform Apply Destroy
      run: terraform apply -auto-approve tfplan-destroy





# name: Terraform AWS Destroy

# on:
#   workflow_dispatch:

# defaults:
#   run:
#     shell: bash

# jobs:
#   destroy:
#     name: 'Terraform Destroy'
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v3
#       with:
#         terraform_version: 1.0.0

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v3
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_REGION }}

#     - name: Terraform Init
#       run: terraform init -upgrade

#     - name: Terraform Format Check
#       run: terraform fmt -check -recursive

#     - name: Terraform Validate
#       run: terraform validate

#     - name: Terraform Plan Destroy
#       run: terraform plan -destroy -out=tfplan

#     - name: Upload Terraform Plan
#       uses: actions/upload-artifact@v3
#       with:
#         name: tfplan
#         path: ./terraform

#     - name: Terraform Destroy
#       run: terraform apply -auto-approve tfplan





# name: Terraform AWS Destroy

# on:
#   workflow_dispatch:

# jobs:
#   terraform_destroy:
#     name: 'Terraform Destroy'
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         terraform_version: 1.0.0

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_REGION }}

#     - name: Terraform Init
#       run: terraform init

#     - name: Terraform Destroy
#       run: terraform destroy -auto-approve